# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

before_script:
 - npm prune
 - npm install
 - npm install -g firebase-tools

stages:
  - build_And_deploy

cache:
  paths:
    - node_modules/
  key: "$CI_BUILD_REPO"

deploy_to_firebase:
 stage: build_And_deploy
 only:
  - master
 script:
  - npm run build
  - firebase deploy --token $FIREBASE_DEPLOY_KEY